# -*- coding: utf-8 -*-
"""Untitled40.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w7j3wuXhNCyDAHf8EM_2jrotuf2PgqIU
"""

#BIG FIVE FUNCTIONS
#1) Sum
#2)Avg: Central tendencacy, Arthematic mean
#3) Minimum    returns the min vlue
#4) Maximun Returens the max value
#5)Count: Returns the abolute count of the data points selected (Numerical columns)

####) Counta : Returns the absolute count of alphabetic columns
####)  Countif: This is required to build the logic iin excel

##) Relative refrencing: When the values change with respect to the rows for an appliwed formula
##) Absolute refrencing:  When the values remain same wrt the rows for an applied formula

###) If coditions